FreeShell: context.c fsh_kill.c fsh_nice.c fsh_ulimit.c functions.c functions_runner.c hashset.c input_parser.c iterator.c main.c tokenizer.c util.c vector.c
	gcc context.c fsh_kill.c fsh_nice.c fsh_ulimit.c functions.c functions_runner.c hashset.c input_parser.c iterator.c main.c tokenizer.c util.c vector.c -lreadline -o FreeShell

