
# Change target to fsh in order to avoid removing FreeShell when recompiling.
Fsh: context.c fsh_kill.c fsh_type.c fsh_nice.c fsh_ulimit.c functions.c functions_runner.c hashset.c input_parser.c iterator.c main.c tokenizer.c util.c vector.c parser_util.c load_functions.c parser_exceptions.c fsh_alias.c fsh_unalias.c
	gcc context.c fsh_kill.c fsh_nice.c fsh_ulimit.c functions.c functions_runner.c hashset.c input_parser.c iterator.c main.c tokenizer.c util.c vector.c parser_util.c load_functions.c parser_exceptions.c fsh_alias.c fsh_unalias.c -lreadline -o FreeShell

