#include <stdio.h>
#include <time.h>
#include <assert.h>
#include <stdlib.h>
#include <ctype.h>
#include <errno.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include "../cgi_runner.h"

// Tests cgi_runner() by injecting fake socket generated by 'socketpair' syscall
int main(int argc, char *argv[]){
    int sduplex[2]; /* Pair of socket descriptors. */

    if (socketpair(AF_UNIX, SOCK_STREAM, 0, sduplex) == -1){
        perror("socketpair syscall");
        return -1;
    }

    struct header_info hinfo;
    hinfo.requested_objname = argv[1];
    hinfo.method = GET;
    hinfo.content_type = "text";
    hinfo.content_length = "4";
    hinfo.host = "google.com";
    hinfo.path_info = "%2Fpinfor%3D";
    hinfo.query_string = "a=bla&b=blu";

    struct config conf;
    conf.ip = "3.2.2.3";
    conf.vhost = "shota.ge";
    conf.document_root = "./my_app/doc_root";
    conf.cgi_bin = "./my_app/test_cgi_bin";
    conf.port = "8888";

    // Body should be less than kernel buffer size when testing
    char body[] = "BODY";
    write(sduplex[0], body, strlen(body) + 1);

    printf ("Script started\n");
    assert (run_cgi_script(&hinfo, sduplex[1], &conf));
    printf ("Script finished, socket should contain output of script\n");

    char reader_buf[1];
    printf (" --> Reading script's output <-- \n");
    while (true){
        int bytes = read(sduplex[0], reader_buf, sizeof(reader_buf));
        if (bytes == -1)
            perror("Error in read");
        if (bytes == 0)
            break;
        printf("%.*s", bytes, reader_buf);
    }
    printf (" --> End reading output <-- \n");

    assert (close(sduplex[0]) == 0);
    return 0;
}
