#include <stdio.h>
#include <assert.h>
#include <stdlib.h>
#include <ctype.h>
#include <errno.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include "../cgi_runner.h"

// Tests cgi_runner() by injecting fake socket generated by 'socketpair' syscall
int main(void){
    int sduplex[2]; /* Pair of socket descriptors. */

    if (socketpair(AF_UNIX, SOCK_STREAM, 0, sduplex) == -1){
        perror("socketpair syscall");
        return -1;
    }

    struct header_info hinfo;
    hinfo.requested_objname = strdup("static_cgi.py");
    hinfo.method = GET;
    hinfo.content_type = "media/jpg";
    hinfo.content_length = "122";

    char body[] = "Http body";
    write(sduplex[0], body, strlen(body) + 1);


    printf ("Script started\n");
    assert (run_cgi_script(&hinfo, sduplex[1]));
    printf ("Script finished, socket should contain output of script\n");

    char reader_buf[1024];
    printf (" --> Reading script's output <-- \n");
    while (true){
        int bytes = read(sduplex[0], reader_buf, sizeof(reader_buf));
        printf("%.*s", bytes, reader_buf);
        if (bytes < sizeof(reader_buf))
            break;
    }
    printf (" --> End reading output <-- \n");

    assert (close(sduplex[0]) == 0);
    
    return 0;
}
